### ISSUE TITLE
Add support for www redirects on cluster

### ISSUE THREAD

**Issue by andreiio** [code4romania/code4ro-k8s#20]

**Comment by Utwo** [comment]
Added in this commits:
https://github.com/code4romania/code4ro-k8s/commit/3e9520f58a5d6d1b5bdd479b18f153ca64897bf1
https://github.com/code4romania/code4ro-k8s/commit/c33d0b59e3c52d4194c3a409d61ec8a8f9c79562
https://github.com/code4romania/code4ro-k8s/commit/039a28078bba019de33ef9a93bf540f4c980e7b4

For the moment only www.centretestarehiv-prod.heroesof.tech is set up.
